name       : suil
version    : 0.10.6
release    : 4
source     :
    - git|https://github.com/drobilla/suil.git : v0.10.6
license    : ISC
component  : programming.library
summary    : A library for loading and wrapping LV2 plugin UIs.
description: |
    Suil makes it possible to load a UI of any toolkit in a host using any other toolkit (assuming the toolkits are both supported by Suil). Hosts do not need to build against or link to foreign toolkit libraries to use UIs written with that toolkit; all the necessary magic is performed by dynamically loaded modules. The API is designed such that hosts do not need to explicitly support specific toolkits at all – if Suil supports a particular toolkit, then UIs in that toolkit will work in all hosts that use Suil automatically.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt5Core)
    - pkgconfig(lv2)
rundeps    :
    - lv2
    - devel :
        - lv2-devel
setup      : |
    %waf_configure --libdir=%libdir%
build      : |
    %waf_build
install    : |
    %waf_install
