name        : suil
version     : 0.8.2
release     : 1
source      :
    - http://download.drobilla.net/suil-0.8.2.tar.bz2 : 787608c1e5b1f5051137dbf77c671266088583515af152b77b45e9c3a36f6ae8
license     : ISC
component   : programming
summary     : A library for loading and wrapping LV2 plugin UIs.
description : |
    Suil makes it possible to load a UI of any toolkit in a host using any other toolkit (assuming the toolkits are both supported by Suil). Hosts do not need to build against or link to foreign toolkit libraries to use UIs written with that toolkit; all the necessary magic is performed by dynamically loaded modules. The API is designed such that hosts do not need to explicitly support specific toolkits at all – if Suil supports a particular toolkit, then UIs in that toolkit will work in all hosts that use Suil automatically.
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(lv2)
setup       : |
    ./waf configure --prefix=/usr --libdir=%libdir% --lv2-system
build       : |
    ./waf build
install     : |
    ./waf install --destdir="$installdir"
